---
#Atualização de cache de repositórios Red Hat
- name: Update / Upgrade Red Hat
  hosts: redhatgroup
  become: yes
  ignore_errors: yes
  tasks:
    - name: Update de cache yum
      yum:
         update_cache: yes 
         
         
#Roda instalação do Apache WebServer Red Hat
- name: Instalação do Apache máquinas Red Hat
  hosts: redhatgroup
  become: yes
  ignore_errors: yes
  tasks:    
    - name: Instalando Apache
      yum:
        name: httpd
        state: present
    - name: Inicializando serviço Apache 
      service:      
        name: httpd
        state: started
        
        
        
#Roda instalação do OpenSCAP Red Hat
- name: Instalação do OpenSCAP máquinas Red hat
  hosts: redhatgroup
  become: yes
  tasks:
    - name: Instalando OpenSCAP Scanner
      yum:        
        name: openscap-scanner
        state: present
        
        
#Roda instalação do Unzip Red Hat
- name: Instalação do Unzip máquinas Red Hat
  hosts: redhatgroup
  become: yes
  tasks:
    - name: Instalando Unzip
      yum:        
        name: unzip
        state: present  
        
        
#Remove o arquivo de download dos arquivos de perfis de varredura antigos Red Hat
- name: Remove o arquivo de download dos perfis de varredura antigos do diretório do OpenSCAP no Red Hat
  hosts: redhatgroup
  become: yes
  tasks:
    - name: Deletando o arquivo .zip de perfis de varredura no Red Hat
      file:
        path: /usr/share/openscap/scap-security-guide-0.1.62.zip
        state: absent    
        
        
#Faz download dos arquivos de perfis de varredura mais atualizados Red Hat
- name: Download do arquivo de profiles de varredura do GitHub para Red Hat
  hosts: redhatgroup
  become: yes
  tasks:
    - name: Execução do download Red Hat
      get_url:
          url: https://github.com/ComplianceAsCode/content/releases/download/v0.1.62/scap-security-guide-0.1.62.zip
          dest: /usr/share/openscap    
          
          
#Extração do conteúdo do arquivo baixado para a pasta /var/repoScap Red Hat
- name: Extração do conteúdo do arquivo baixado para o diretório do OpenSCAP Red Hat
  hosts: redhatgroup
  become: yes
  tasks:
    - name: Extraindo arquivos Red Hat
      unarchive:
          src: /usr/share/openscap/scap-security-guide-0.1.62.zip
          dest: /usr/share/openscap
          remote_src: yes  
          
          
#Criação do diretório de resultados das varreduras Red Hat
- name: Criação de diretório /opt/scanResults para o Red Hat
  hosts: redhatgroup
  become: yes
  tasks:
    - name: Criando diretório no Red Hat
      file:
        path: /opt/scanResults
        state: directory   
        
        
#Entrada no diretório onde ficam os perfis do OpenSCAP e execução do perfil SSG adequado a cada sistema
- name: Fase de execução do OpenSCAP em busca de vulnerabilidade no Red Hat
  hosts: redhatgroup
  become: yes
  ignore_errors: yes
  tasks:
    - name: Executando o OpenSCAP em busca de vulnerabildiades no Red Hat 
      command: 
          cmd: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_server_l1 --results /opt/scanResults/scan1.xml --report /opt/scanResults/scan1.html /usr/share/openscap/scap-security-guide-0.1.62/ssg-rhel8-ds-1.2.xml
          chdir: /usr/share/openscap/scap-security-guide-0.1.62
          
          
#Remove o arquivo .html do scan passado que estava na pasta do Apache
- name: Remove o arquivo .html do scan passado que estava na pasta do Apache no Red Hat
  hosts: redhatgroup
  become: yes
  ignore_errors: yes
  tasks:
    - name: Deletando o arquivo .html do diretório /var/www/html no Red Hat
      file:
        path: /var/www/html/scan1.html
        state: absent       
        
        
#Cópia do arquivo scan1.html para a pasta do Apache para consulta pelo browser (http://ip_do_servidor/scan1.html)
- name: Cópia do arquivo scan1.html para a pasta do Apache no Red Hat
  hosts: redhatgroup
  become: yes
  tasks:
    - name: Copiando arquivo de resultado para a pasta do Apache no Red Hat
      file:
          src: /opt/scanResults/scan1.html
          dest: /var/www/html/scan1.html
          state: link                                                                                            
