---
#Remove o arquivo de resultado da remediação (caso exista)
- name: Remove o arquivo remediate.sh do generate fix /opt/scanResults/
  hosts: redhatgroup
  become: yes
  ignore_errors: yes
  tasks:
    - name: Deletando o arquivo remediate.sh do /opt/scanResults/ no Red Hat
      file:
        path: /opt/scanResults/remediate.sh
        state: absent  
        
#Script de geração de remediação do OpenSCAP
- name: Roda script generate fix no Red Hat
  hosts: redhatgroup
  become: yes
  ignore_errors: yes
  tasks:
    - name: Executando o generate fix no Red Hat 
      command: 
          cmd: oscap xccdf generate fix --fix-type bash --output remediate.sh --result-id xccdf_org.ssgproject.content_profile_cis_server_l1 /opt/scanResults/scan1.xml 
          chdir: /opt/scanResults/
          
