#Atualização de cache de repositórios Red Hat
- name: Update / Upgrade Red Hat
  hosts: redhatgroup
  become: yes
  ignore_errors: yes
  tasks:
    - name: Update de cache yum
      yum:
         update_cache: yes 
    - name: Instala atualizações
      yum:      
         name: '*'
         state: latest
